const PROJECT_ALL_PERMISSIONS = [
  "VIEW_FINANCIAL_METRICS",
  "EXPORT_FINANCIAL_REPORTS",
  "VIEW_DONATORS_LIST",
  "VIEW_DONATIONS_LIST",
  "VIEW_SETTINGS",
  "VIEW_SETTINGS_NOTIFICATION",
  "VIEW_SETTINGS_GENERAL",
  "VIEW_SETTINGS_PAGE",
  "VIEW_SETTINGS_PAYMENT",
  "VIEW_SETTINGS_FORM",
  "VIEW_FINANCIAL_TRANSFERS",
  "VIEW_FINANCIAL_STATEMENTS",
  "VIEW_NOTIFICATION_SENTS",
  "VIEW_DONATOR_REPORTS",
  "VIEW_FINANCIAL_REPORTS",
] as const;

export { PROJECT_ALL_PERMISSIONS };
